# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

minReadySeconds: 5
preStopSleepSeconds: 5
networkTester:
  image:
    repository: cr.yandex/crp1of6bddata8ain3q5/k8s-network-tester
    tag: latest

app:
  image:
    repository: cr.yandex/crp1of6bddata8ain3q5/search-demo

  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      memory: 6Gi

env:
  WEB_CONCURRENCY: 1
  CLICKHOUSE_URL: http://chi-clickhouse-search-0-0:8123

clusterService:
  ports:
    http: 8080

tls:
  secretName: tls-certificates
