# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

minReadySeconds: 5
preStopSleepSeconds: 5
networkTester:
  image:
    repository: cr.yandex/crp1of6bddata8ain3q5/k8s-network-tester
    tag: latest

app:
  image:
    repository: cr.yandex/crp1of6bddata8ain3q5/search-demo

  resources:
    requests:
      cpu: 0.01
      memory: 50Mi
    limits:
      memory: 100Mi

env:
  WEB_CONCURRENCY: 1

clusterService:
  ports:
    http: 8080

tls:
  secretName: tls-certificates
