apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "search_demo.fullname" . }}
  labels:
    {{- include "search_demo.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "search_demo.selectorLabels" . | nindent 6 }}
