apiVersion: v1
kind: Service
metadata:
  name: {{ include "search_demo.fullname" . }}-cluster
  labels:
    {{- include "search_demo.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.clusterService.ports.http }}
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "search_demo.selectorLabels" . | nindent 4 }}
