{{- if .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "search_demo.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    {{- include "search_demo.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.class | quote }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.tls.secretName }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ include "search_demo.ingressPath" . }}(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "search_demo.fullname" . }}-cluster
                port:
                  number: {{ .Values.clusterService.ports.http }}
{{- end }}
